"""
app/agents/response_generator.py - Response Generator Agent
"""

from typing import Dict, Any, List, Optional
from app.services.llm_gateway import LLMGateway
from app.core.logging import get_logger

logger = get_logger(__name__)


class ResponseGenerator:
    """
    Generates final responses using the LLM.
    """
    
    def __init__(self):
        self.llm = LLMGateway()
    
    def generate(
        self,
        query: str,
        context: str,
        language: str = "English",
        query_type: str = "general",
        max_tokens: int = 500
    ) -> Dict[str, Any]:
        """
        Generate a response using the LLM.
        
        Args:
            query: User's question
            context: Context for the LLM
            language: Response language
            query_type: Type of query (case, legal, general)
            max_tokens: Maximum tokens in response
        
        Returns:
            Dictionary with response and metadata
        """
        # Build system prompt
        system_prompt = self._build_system_prompt(language, query_type)
        
        # Build user prompt
        user_prompt = self._build_user_prompt(query, context, language)
        
        # Generate response
        response = self.llm.generate(
            prompt=user_prompt,
            system_prompt=system_prompt,
            max_tokens=max_tokens,
            temperature=0.7
        )
        
        if response.get("success"):
            logger.info(f"✅ Response generated by {response.get('provider')}")
        else:
            logger.error(f"❌ Response generation failed: {response}")
        
        return response
    
    def _build_system_prompt(self, language: str, query_type: str) -> str:
        """Build the system prompt."""
        language_note = f"Respond in {language} language." if language != "English" else ""
        
        prompts = {
            "case": f"""You are a helpful legal assistant specializing in Indian court cases.
{language_note}
Use the case context provided to answer the user's question.
Be clear, concise, and accurate.
If you don't know something, say so.
Focus on the specific case details provided.""",

            "legal": f"""You are a knowledgeable legal assistant specializing in Indian law.
{language_note}
Use the legal knowledge provided to answer the user's question.
Cite relevant sections and acts when appropriate.
Explain legal terms in simple language.
Provide practical, actionable information.""",

            "general": f"""You are a helpful legal assistant.
{language_note}
Answer the user's question to the best of your knowledge.
If it's outside your scope, politely say so.
Be friendly and helpful."""
        }
        
        return prompts.get(query_type, prompts["general"])
    
    def _build_user_prompt(self, query: str, context: str, language: str) -> str:
        """Build the user prompt."""
        if context:
            return f"""Context:
{context}

Question: {query}

Please provide a helpful answer based on the context above."""
        else:
            return f"""Question: {query}

Please provide a helpful answer."""
    
    def generate_with_sources(
        self,
        query: str,
        context: str,
        sources: List[Dict[str, Any]],
        language: str = "English",
        query_type: str = "general"
    ) -> Dict[str, Any]:
        """
        Generate response with source citations.
        
        Args:
            query: User's question
            context: Context for the LLM
            sources: List of sources
            language: Response language
            query_type: Type of query
        
        Returns:
            Dictionary with response and sources
        """
        # Generate base response
        result = self.generate(query, context, language, query_type)
        
        if result.get("success"):
            # Add sources to response
            answer = result.get("response", "")
            
            # Add sources section
            if sources:
                answer += "\n\n📚 **Sources:**\n"
                for i, source in enumerate(sources[:5], 1):
                    title = source.get("title", "Document")
                    score = source.get("relevance_score", 0)
                    answer += f"{i}. {title} (Relevance: {score:.2f})\n"
            
            result["response"] = answer
            result["sources"] = sources
        
        return result